operator:
  replicas: 1
  revisionHistoryLimit: 1
  image: pannoi/kollektor
  version: 1.0.4
  config:
    scrape:
      githubTokenSecret: ""
      interval: "1h"
    slack:
      clusterName: default
      enabled: false
      webhookUrlSecret: ""
